# Generated by Django 4.1.2 on 2022-10-20 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='user',
        ),
        migrations.RemoveField(
            model_name='itemuser',
            name='item',
        ),
        migrations.RemoveField(
            model_name='itemuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='family_group',
        ),
        migrations.RemoveField(
            model_name='user',
            name='items',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='Family',
        ),
        migrations.DeleteModel(
            name='FamilyGroup',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='ItemUser',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
