# Generated by Django 4.1.2 on 2022-12-04 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, unique=True)),
                ('mail', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('avatar', models.ImageField(null=True, upload_to='')),
                ('family_group', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.familygroup')),
                ('items', models.ManyToManyField(null=True, to='app.item')),
            ],
        ),
        migrations.DeleteModel(
            name='AuthToken',
        ),
        migrations.RemoveField(
            model_name='user',
            name='family_group',
        ),
        migrations.RemoveField(
            model_name='user',
            name='items',
        ),
        migrations.DeleteModel(
            name='UserAuthModel',
        ),
        migrations.RenameModel(
            old_name='ItemUser',
            new_name='ItemPlayer',
        ),
        migrations.AlterField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.player'),
        ),
        migrations.AlterField(
            model_name='family',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.player'),
        ),
        migrations.AlterField(
            model_name='itemplayer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.player'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
