# Generated by Django 4.1.2 on 2022-11-24 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_userauthmodel_id_alter_userauthmodel_password_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthToken',
        ),
        migrations.DeleteModel(
            name='UserAuthModel',
        ),
        migrations.AlterField(
            model_name='user',
            name='family_group',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.familygroup'),
        ),
    ]
