# Generated by Django 4.1.2 on 2022-11-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_authtoken_delete_userauthmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='items',
            field=models.ManyToManyField(null=True, to='app.item'),
        ),
    ]
