# Generated by Django 4.1.2 on 2022-11-12 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_authmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthModel',
        ),
    ]
